// Code generated by MockGen. DO NOT EDIT.
// Source: github.go

// Package mikku is a generated GoMock package.
package mikku

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	github "github.com/google/go-github/v28/github"
	reflect "reflect"
)

// MockGitHubRepositoriesClient is a mock of GitHubRepositoriesClient interface
type MockGitHubRepositoriesClient struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubRepositoriesClientMockRecorder
}

// MockGitHubRepositoriesClientMockRecorder is the mock recorder for MockGitHubRepositoriesClient
type MockGitHubRepositoriesClientMockRecorder struct {
	mock *MockGitHubRepositoriesClient
}

// NewMockGitHubRepositoriesClient creates a new mock instance
func NewMockGitHubRepositoriesClient(ctrl *gomock.Controller) *MockGitHubRepositoriesClient {
	mock := &MockGitHubRepositoriesClient{ctrl: ctrl}
	mock.recorder = &MockGitHubRepositoriesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGitHubRepositoriesClient) EXPECT() *MockGitHubRepositoriesClientMockRecorder {
	return m.recorder
}

// CreateRelease mocks base method
func (m *MockGitHubRepositoriesClient) CreateRelease(ctx context.Context, owner, repo string, release *github.RepositoryRelease) (*github.RepositoryRelease, *github.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRelease", ctx, owner, repo, release)
	ret0, _ := ret[0].(*github.RepositoryRelease)
	ret1, _ := ret[1].(*github.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateRelease indicates an expected call of CreateRelease
func (mr *MockGitHubRepositoriesClientMockRecorder) CreateRelease(ctx, owner, repo, release interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRelease", reflect.TypeOf((*MockGitHubRepositoriesClient)(nil).CreateRelease), ctx, owner, repo, release)
}

// GetLatestRelease mocks base method
func (m *MockGitHubRepositoriesClient) GetLatestRelease(ctx context.Context, owner, repo string) (*github.RepositoryRelease, *github.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestRelease", ctx, owner, repo)
	ret0, _ := ret[0].(*github.RepositoryRelease)
	ret1, _ := ret[1].(*github.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLatestRelease indicates an expected call of GetLatestRelease
func (mr *MockGitHubRepositoriesClientMockRecorder) GetLatestRelease(ctx, owner, repo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestRelease", reflect.TypeOf((*MockGitHubRepositoriesClient)(nil).GetLatestRelease), ctx, owner, repo)
}

// GetContents mocks base method
func (m *MockGitHubRepositoriesClient) GetContents(ctx context.Context, owner, repo, path string, opt *github.RepositoryContentGetOptions) (*github.RepositoryContent, []*github.RepositoryContent, *github.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContents", ctx, owner, repo, path, opt)
	ret0, _ := ret[0].(*github.RepositoryContent)
	ret1, _ := ret[1].([]*github.RepositoryContent)
	ret2, _ := ret[2].(*github.Response)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetContents indicates an expected call of GetContents
func (mr *MockGitHubRepositoriesClientMockRecorder) GetContents(ctx, owner, repo, path, opt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContents", reflect.TypeOf((*MockGitHubRepositoriesClient)(nil).GetContents), ctx, owner, repo, path, opt)
}

// UpdateFile mocks base method
func (m *MockGitHubRepositoriesClient) UpdateFile(ctx context.Context, owner, repo, path string, opt *github.RepositoryContentFileOptions) (*github.RepositoryContentResponse, *github.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFile", ctx, owner, repo, path, opt)
	ret0, _ := ret[0].(*github.RepositoryContentResponse)
	ret1, _ := ret[1].(*github.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateFile indicates an expected call of UpdateFile
func (mr *MockGitHubRepositoriesClientMockRecorder) UpdateFile(ctx, owner, repo, path, opt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFile", reflect.TypeOf((*MockGitHubRepositoriesClient)(nil).UpdateFile), ctx, owner, repo, path, opt)
}

// MockGitHubPullRequestsClient is a mock of GitHubPullRequestsClient interface
type MockGitHubPullRequestsClient struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubPullRequestsClientMockRecorder
}

// MockGitHubPullRequestsClientMockRecorder is the mock recorder for MockGitHubPullRequestsClient
type MockGitHubPullRequestsClientMockRecorder struct {
	mock *MockGitHubPullRequestsClient
}

// NewMockGitHubPullRequestsClient creates a new mock instance
func NewMockGitHubPullRequestsClient(ctrl *gomock.Controller) *MockGitHubPullRequestsClient {
	mock := &MockGitHubPullRequestsClient{ctrl: ctrl}
	mock.recorder = &MockGitHubPullRequestsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGitHubPullRequestsClient) EXPECT() *MockGitHubPullRequestsClientMockRecorder {
	return m.recorder
}

// List mocks base method
func (m *MockGitHubPullRequestsClient) List(ctx context.Context, owner, repo string, opt *github.PullRequestListOptions) ([]*github.PullRequest, *github.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, owner, repo, opt)
	ret0, _ := ret[0].([]*github.PullRequest)
	ret1, _ := ret[1].(*github.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List
func (mr *MockGitHubPullRequestsClientMockRecorder) List(ctx, owner, repo, opt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGitHubPullRequestsClient)(nil).List), ctx, owner, repo, opt)
}

// Create mocks base method
func (m *MockGitHubPullRequestsClient) Create(ctx context.Context, owner, repo string, pull *github.NewPullRequest) (*github.PullRequest, *github.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, owner, repo, pull)
	ret0, _ := ret[0].(*github.PullRequest)
	ret1, _ := ret[1].(*github.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create
func (mr *MockGitHubPullRequestsClientMockRecorder) Create(ctx, owner, repo, pull interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGitHubPullRequestsClient)(nil).Create), ctx, owner, repo, pull)
}

// MockGitHubGitClient is a mock of GitHubGitClient interface
type MockGitHubGitClient struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubGitClientMockRecorder
}

// MockGitHubGitClientMockRecorder is the mock recorder for MockGitHubGitClient
type MockGitHubGitClientMockRecorder struct {
	mock *MockGitHubGitClient
}

// NewMockGitHubGitClient creates a new mock instance
func NewMockGitHubGitClient(ctrl *gomock.Controller) *MockGitHubGitClient {
	mock := &MockGitHubGitClient{ctrl: ctrl}
	mock.recorder = &MockGitHubGitClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGitHubGitClient) EXPECT() *MockGitHubGitClientMockRecorder {
	return m.recorder
}

// GetRef mocks base method
func (m *MockGitHubGitClient) GetRef(ctx context.Context, owner, repo, ref string) (*github.Reference, *github.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRef", ctx, owner, repo, ref)
	ret0, _ := ret[0].(*github.Reference)
	ret1, _ := ret[1].(*github.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRef indicates an expected call of GetRef
func (mr *MockGitHubGitClientMockRecorder) GetRef(ctx, owner, repo, ref interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRef", reflect.TypeOf((*MockGitHubGitClient)(nil).GetRef), ctx, owner, repo, ref)
}

// CreateRef mocks base method
func (m *MockGitHubGitClient) CreateRef(ctx context.Context, owner, repo string, ref *github.Reference) (*github.Reference, *github.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRef", ctx, owner, repo, ref)
	ret0, _ := ret[0].(*github.Reference)
	ret1, _ := ret[1].(*github.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateRef indicates an expected call of CreateRef
func (mr *MockGitHubGitClientMockRecorder) CreateRef(ctx, owner, repo, ref interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRef", reflect.TypeOf((*MockGitHubGitClient)(nil).CreateRef), ctx, owner, repo, ref)
}
