name: Go tests
on: pull_request

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - uses: actions/checkout@v1
      - name: Execute tests
        run: go test -v .